name: ftp-action
uses: sebastianpopp/ftp-action@v2.0.0
  with:
  host: ${{ secrets.FTP_SERVER }}
  user: ${{ secrets.FTP_USERNAME }}
  password: ${{ secrets.FTP_PASSWORD }}
  remoteDir: "q930933x.beget.tech/public_html/"
